package exceptions

import "errors"

var FailedVerify = errors.New("验证失败！")
